//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public int location_id { get; set; }
        public int location_type { get; set; }
        public int user_id { get; set; }
        public string text { get; set; }
        public bool deleted { get; set; }
        public System.DateTime date { get; set; }
        public int last_modified_by_id { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual user last_modified_by { get; set; }
    }
}
