//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facebook_connection
    {
        public int id { get; set; }
        public string facebook_user_id { get; set; }
        public string access_token { get; set; }
        public Nullable<System.DateTime> access_token_expiration { get; set; }
        public bool notifications_enabled { get; set; }
        public bool automatic_sharing_enabled { get; set; }
    
        public virtual user user { get; set; }
    }
}
