//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustPressPlayDBEntities : DbContext
    {
        public JustPressPlayDBEntities()
            : base("name=JustPressPlayDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<user> user { get; set; }
        public DbSet<achievement_template> achievement_template { get; set; }
        public DbSet<achievement_instance> achievement_instance { get; set; }
        public DbSet<achievement_requirement> achievement_requirement { get; set; }
        public DbSet<achievement_caretaker> achievement_caretaker { get; set; }
        public DbSet<achievement_user_content> achievement_user_content { get; set; }
        public DbSet<achievement_user_content_pending> achievement_user_content_pending { get; set; }
        public DbSet<achievement_user_story> achievement_user_story { get; set; }
        public DbSet<friend> friend { get; set; }
        public DbSet<friend_pending> friend_pending { get; set; }
        public DbSet<log> log { get; set; }
        public DbSet<notification> notifications { get; set; }
        public DbSet<quest_template> quest_template { get; set; }
        public DbSet<quest_achievement_step> quest_achievement_step { get; set; }
        public DbSet<quest_instance> quest_instance { get; set; }
        public DbSet<quest_tracking> quest_tracking { get; set; }
        public DbSet<system_stat> system_stat { get; set; }
        public DbSet<external_token> external_token { get; set; }
        public DbSet<search_keyword> search_keyword { get; set; }
        public DbSet<achievement_keyword> achievement_keyword { get; set; }
        public DbSet<quest_keyword> quest_keyword { get; set; }
        public DbSet<comment> comment { get; set; }
    }
}
