//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public System.DateTime timestamp { get; set; }
        public int user_id { get; set; }
        public string ip_address { get; set; }
        public string action { get; set; }
        public string value_1 { get; set; }
        public string value_2 { get; set; }
        public Nullable<int> id_1 { get; set; }
        public Nullable<int> id_2 { get; set; }
        public string id_type_1 { get; set; }
        public string id_type_2 { get; set; }
    
        public virtual user user { get; set; }
    }
}
