//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public int source_id { get; set; }
        public int destination_id { get; set; }
        public System.DateTime date { get; set; }
        public string message { get; set; }
        public string icon { get; set; }
        public string url { get; set; }
    
        public virtual user source { get; set; }
        public virtual user destination { get; set; }
    }
}
