//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_instance
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int quest_id { get; set; }
        public System.DateTime completed_date { get; set; }
        public bool comments_disabled { get; set; }
        public bool globally_assigned { get; set; }
    
        public virtual user user { get; set; }
        public virtual quest_template quest_template { get; set; }
    }
}
