//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_keyword
    {
        public int id { get; set; }
        public int keyword_id { get; set; }
        public int quest_id { get; set; }
    
        public virtual quest_template quest_template { get; set; }
        public virtual search_keyword keyword { get; set; }
    }
}
