//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class search_keyword
    {
        public search_keyword()
        {
            this.achievement_keyword = new HashSet<achievement_keyword>();
            this.quest_keyword = new HashSet<quest_keyword>();
        }
    
        public int id { get; set; }
        public string keyword { get; set; }
    
        public virtual ICollection<achievement_keyword> achievement_keyword { get; set; }
        public virtual ICollection<quest_keyword> quest_keyword { get; set; }
    }
}
