//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend_pending
    {
        public int id { get; set; }
        public int source_id { get; set; }
        public int destination_id { get; set; }
        public System.DateTime request_date { get; set; }
        public bool ignored { get; set; }
    
        public virtual user source { get; set; }
        public virtual user destination { get; set; }
    }
}
