//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustPressPlay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_stat
    {
        public int id { get; set; }
        public int total_players { get; set; }
        public int total_possible_achievements { get; set; }
        public int total_attained_achievements { get; set; }
        public int total_possible_quests { get; set; }
        public int total_completed_quests { get; set; }
        public int total_possible_points_create { get; set; }
        public int total_possible_points_explore { get; set; }
        public int total_possible_points_learn { get; set; }
        public int total_possible_points_socialize { get; set; }
        public int total_attained_points_create { get; set; }
        public int total_attained_points_explore { get; set; }
        public int total_attained_points_learn { get; set; }
        public int total_attained_points_socialize { get; set; }
    }
}
